name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install NDK
      run: |
           echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
           echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.1.5948944" --sdk_root=${ANDROID_SDK_ROOT}

    - name: Build with Gradle
      run: cd android-refimpl-app ; ./gradlew assembleRelease

    - name: upload apk
      uses: actions/upload-artifact@v3
      with:
        name: trifa
        path: /home/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/app/build/outputs/apk/debug/app-debug.apk

  gradle-wrapper-validation:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1.0.4

  android-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install cliclick
      run:  brew install cliclick

    - name: install java11
      run:  brew install java11

    - name: macos-version1
      run: sw_vers -productVersion

    - name: macos-version2
      run: system_profiler SPSoftwareDataType

    - name: android test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        # ndk: 16.1.4479499
        # ndk: 21.0.6113669
        ndk: 20.1.5948944
        emulator-options: -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
        script: |
          rm -f /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/app/witness.gradle
          printf 'dependencyVerification {\nverify = [\n]\n}\n' > /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/app/witness.gradle
          export PATH="/usr/local/opt/openjdk@11/bin:$PATH"
          cd android-refimpl-app ; ./gradlew assemble
          cliclick -m verbose m:12,34
          screencapture -T 42 -x -t png /Users/runner/screen01.png &
          screencapture -T 43 -x -t png /Users/runner/screen02.png &
          screencapture -T 43 -x -t png /Users/runner/screen03.png &
          screencapture -T 44 -x -t png /Users/runner/screen04.png &
          screencapture -T 45 -x -t png /Users/runner/screen05.png &
          screencapture -T 46 -x -t png /Users/runner/screen06.png &
          screencapture -T 50 -x -t png /Users/runner/screen07.png &
          screencapture -T 51 -x -t png /Users/runner/screen08.png &
          screencapture -T 52 -x -t png /Users/runner/screen09.png &
          screencapture -T 53 -x -t png /Users/runner/screen10.png &
          screencapture -T 60 -x -t png /Users/runner/screen11.png &
          screencapture -T 61 -x -t png /Users/runner/screen12.png &
          screencapture -T 62 -x -t png /Users/runner/screen13.png &
          screencapture -T 63 -x -t png /Users/runner/screen14.png &
          screencapture -T 64 -x -t png /Users/runner/screen15.png &
          screencapture -T 65 -x -t png /Users/runner/screen16.png &
          screencapture -T 66 -x -t png /Users/runner/screen17.png &
          screencapture -T 67 -x -t png /Users/runner/screen18.png &
          screencapture -T 68 -x -t png /Users/runner/screen19.png &
          screencapture -T 69 -x -t png /Users/runner/screen20.png &
          screencapture -T 240 -x -t png /Users/runner/screen99.png &
          cd android-refimpl-app ; ./gradlew connectedAndroidTest || echo "NOERR"

    - name: upload screenshots
      uses: actions/upload-artifact@v3
      with:
        name: macscreen
        path: |
          /Users/runner/screen*.png
