name: Bob Tests
on:
  push:
    paths-ignore:
     - 'README.md'
     - '.github/workflows/android.yml'
  pull_request:
    paths-ignore:
     - 'README.md'
     - '.github/workflows/android.yml'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:
  android-test_bob:
    runs-on: macos-latest
    permissions:
      contents: write
    if: ${{ true }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: |
          11

    - name: test java1
      run:  |
            type java
            echo "===========1========="
            java -version || exit 0
            echo "===========2========="

    - name: install cliclick
      run:  brew install cliclick

    - name: install imagemagick
      run:  brew install imagemagick

    - name: macos-version1
      run: sw_vers -productVersion

    - name: macos-version2
      run: system_profiler SPSoftwareDataType

    - name: download tester
      shell: bash
      run: |
           curl -L https://github.com/zoff99/java_tox_tester/archive/refs/heads/master.zip -o master.zip
           unzip master.zip
           ls -al java_tox_tester-master/
           java -version
           javac -version

    - name: start tester
      shell: bash
      run: |
           cd java_tox_tester-master/ ; ls -al ; ./do_wait_for_app.sh &

    - name: android test
      timeout-minutes: 120
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 31
        profile: Nexus 6
        arch: x86_64
        ndk: 21.0.6113669
        cmake: 3.10.2.4988404
        emulator-options: -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        disable-spellchecker: true
        script: |
          rm -f /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/app/witness.gradle
          sed -i -e 's#a.getWindow().addFlags#//a.getWindow().addFlagsXXYY#' /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/app/src/main/java/com/zoffcc/applications/trifa/CallingActivity.java
          printf 'dependencyVerification {\nverify = [\n]\n}\n' > /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/app/witness.gradle
          java -version
          cd android-refimpl-app ; ./gradlew assemble
          cliclick -m verbose m:12,34
          adb logcat -c || echo "NOERR"
          adb logcat > /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/logcat.txt &
          echo 'sleep 100' > /Users/runner/a.sh
          echo 'sleep 40' >> /Users/runner/a.sh
          echo 'sleep 10' >> /Users/runner/a.sh
          echo 'sleep 10' >> /Users/runner/a.sh
          echo 'sleep 10' >> /Users/runner/a.sh
          echo 'adb pull "/storage/emulated/0/screen4.png" /Users/runner/screen_adb_04.png' >> /Users/runner/a.sh
          cat /Users/runner/a.sh
          ls -al /Users/runner/a.sh
          chmod u+rx /Users/runner/a.sh
          bash /Users/runner/a.sh &
          cd android-refimpl-app ; ./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.zoffcc.applications.trifa.JavaFriendTester || echo "NOERR"
          pwd
          adb pull /sdcard/googletest/test_outputfiles .
          ls -al /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/test_outputfiles/
          echo "---------------"
          ls -al /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/test_outputfiles/*.png

    - name: put datetime on screenshots
      run:  |
            cd /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/
            git rev-parse --short HEAD
            c="$(git rev-parse --short HEAD)"
            cd /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/test_outputfiles/
            ls -al
            d="$(date '+%Y-%m-%d %H:%M:%S')"
            convert test_004b.png -gravity SouthEast -pointsize 62 -fill white -annotate +30+30 "$d ($c)" test_004b_time.png
            convert test_099.png -gravity SouthEast -pointsize 62 -fill white -annotate +30+30 "$d ($c)" test_099_time.png
            mv test_004b_time.png test_004b.png
            mv test_099_time.png test_099.png

    - name: upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: macscreen
        path: |
          /Users/runner/screen*.png
          /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/test_outputfiles/*.png

    - name: upload logcat output
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: logcat
        path: |
          /Users/runner/work/ToxAndroidRefImpl/ToxAndroidRefImpl/android-refimpl-app/logcat.txt

